apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mta-tackle
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/konveyor/tackle
    targetRevision: main
    path: deploy/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: konveyor-tackle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
